
//GET para buscar Todos
GET http://127.0.0.1:5005/produtos

###

//get por ID
GET http://[::1]:5005/produto/3 HTTP/1.1

###

POST http://127.0.0.1:5005/produtos HTTP/1.1
Content-Type: application/json

{
    "nome": "Iphone XR",
    "categoria": "Celular",
    "preco": 1.500,
    "desconto": 0.3   
}

###

PUT http://127.0.0.1:5005/produtos/6
Content-Type: application/json

{
    "nome": "Teste01",
    "preco": 2.999
}

###

DELETE http://[::1]:5005/produtos/8
